export const IS_LOADING = "IS_LOADING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_FALED = "USER_DATA_FALED";
export const USER_LOGOUT = "USER_LOGOUT";

export const SIGNUP_USER_SUCCESS = "SIGNUP_USER_SUCCESS";
export const SIGNUP_USER_FALED = "SIGNUP_USER_FALED";
